import { test, expect } from '@playwright/test';
test('front user management, role scopes, JSON drawer and session revocation', async ({ page, request }, info) => {
  const prefix = `browser_${Date.now()}`;
  const account = `${prefix}_user`;
  const password = 'Browser-user-123!';
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/web-cms/');
  await page.getByPlaceholder('用户名').fill('admin');
  await page.getByPlaceholder('密码', { exact: true }).fill('123456');
  await page.getByRole('button', { name: '登 录' }).click();
  await expect(page.getByText('前台用户管理', {exact:true}).first()).toBeVisible();
  await expect(page.getByText('图书管理',{exact:true})).toHaveCount(0);
  await page.goto('/web-cms/#/admin/roles');
  await page.getByRole('tab', { name: '前台角色', exact:true }).click();
  await page.getByRole('button', { name: /添加角色/ }).click();
  let drawer = page.locator('.ant-drawer-content');
  await expect(drawer.getByText('添加前台角色',{exact:true})).toBeVisible();
  await drawer.getByLabel('角色标识', {exact:true}).fill(`${prefix}_app`);
  await drawer.getByLabel('角色名称', {exact:true}).fill(`${prefix}_前台`);
  await expect(drawer.getByText('尚未声明前台业务权限，可先创建无权限角色。')).toBeVisible();
  await drawer.getByRole('button', {name:'保 存'}).click();
  await expect(drawer).toBeHidden();
  await expect(page.getByRole('cell',{name:`${prefix}_前台`,exact:true})).toBeVisible();
  await page.getByRole('tab', { name: '后台角色', exact:true }).click();
  await expect(page.getByRole('cell',{name:`${prefix}_前台`,exact:true})).toHaveCount(0);
  await page.getByRole('button', { name: /添加角色/ }).click();
  await drawer.getByLabel('角色标识', {exact:true}).fill(`${prefix}_admin`);
  await drawer.getByLabel('角色名称', {exact:true}).fill(`${prefix}_后台`);
  await expect(drawer.getByText('查看用户',{exact:true})).toBeVisible();
  await drawer.getByRole('button', {name:'保 存'}).click();
  await expect(drawer).toBeHidden();
  await page.getByText('前台用户管理',{exact:true}).first().click();
  await page.getByRole('button',{name:/新建用户/}).click();
  drawer = page.locator('.ant-drawer-content');
  await drawer.getByLabel('登录账号',{exact:true}).fill(account);
  await drawer.getByLabel('昵称',{exact:true}).fill('浏览器验收用户');
  await drawer.getByLabel('初始密码',{exact:true}).fill(password);
  await drawer.getByLabel('前台角色',{exact:true}).click();
  await expect(page.locator('.ant-select-item-option').filter({hasText:`${prefix}_后台`})).toHaveCount(0);
  await page.locator('.ant-select-item-option').filter({hasText:`${prefix}_前台`}).click();
  await drawer.getByLabel('昵称',{exact:true}).click();
  await drawer.getByLabel('JSON 资料',{exact:true}).fill('[]');
  await drawer.getByRole('button',{name:'保 存'}).click();
  await expect(drawer.getByText('请输入有效的 JSON 对象，例如 {}。')).toBeVisible();
  await drawer.getByLabel('JSON 资料',{exact:true}).fill('{"city":"杭州","preferences":{"theme":"dark"}}');
  await page.screenshot({path:info.outputPath('app-user-drawer.png'),fullPage:true});
  await drawer.getByRole('button',{name:'保 存'}).click();
  await expect(drawer).toBeHidden();
  let row = page.getByRole('row').filter({has:page.getByRole('cell',{name:account,exact:true})});
  await expect(row).toBeVisible();
  await page.reload();
  await expect(row).toBeVisible();
  await row.getByRole('button',{name:'编辑',exact:true}).click();
  await expect(drawer.getByLabel('JSON 资料',{exact:true})).toContainText('杭州');
  await drawer.getByLabel('昵称',{exact:true}).fill('用户资料已修改');
  await drawer.getByRole('button',{name:'保 存'}).click();
  await expect(row.getByRole('cell',{name:'用户资料已修改',exact:true})).toBeVisible();
  const login = async (pass=password) => {
    const res = await request.post('/api/app/auth/login',{data:{account,password:pass}});
    expect(res.status()).toBe(200);return (await res.json()).token;
  };
  let token = await login();
  await row.getByRole('button',{name:'强制下线',exact:true}).click();
  await page.getByRole('button',{name:'确 定',exact:true}).click();
  await expect(page.getByText('操作成功',{exact:true}).last()).toBeVisible();
  expect((await request.get('/api/app/auth/me',{headers:{authorization:`Bearer ${token}`}})).status()).toBe(401);
  token = await login();
  await row.getByRole('button',{name:'停用',exact:true}).click();
  await page.getByRole('button',{name:'确 定',exact:true}).click();
  await expect(row.getByText('停用',{exact:true})).toBeVisible();
  expect((await request.get('/api/app/auth/me',{headers:{authorization:`Bearer ${token}`}})).status()).toBe(401);
  await row.getByRole('button',{name:'启用',exact:true}).click();
  await page.getByRole('button',{name:'确 定',exact:true}).click();
  await expect(row.getByText('正常',{exact:true})).toBeVisible();
  token = await login();
  await row.getByRole('button',{name:'重置密码',exact:true}).click();
  await drawer.getByLabel('新密码',{exact:true}).fill('Reset-browser-123!');
  await drawer.getByRole('button',{name:'保 存'}).click();
  await expect(drawer).toBeHidden();
  expect((await request.get('/api/app/auth/me',{headers:{authorization:`Bearer ${token}`}})).status()).toBe(401);
  await login('Reset-browser-123!');
  await page.screenshot({path:info.outputPath('app-users.png'),fullPage:true});
  expect(errors).toEqual([]);
});
