import {test, expect} from '@playwright/test';
test('real login, request editor, auth isolation and desktop layouts', async ({page}, testInfo) => {
  const account = process.env.E2E_ADMIN_ACCOUNT ?? 'admin';
  const password = process.env.E2E_ADMIN_PASSWORD ?? '123456';
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('requestfailed', request => console.log('Request failed:', new URL(request.url()).pathname, request.failure()?.errorText));
  await page.goto('/web-cms/');
  await page.getByPlaceholder('用户名').fill(account);
  await page.getByPlaceholder('密码', { exact: true }).fill(password);
  await page.getByRole('button', {name:'登 录'}).click();
  if (!await page.getByText('开发工具',{exact:true}).first().isVisible()) await page.getByText('系统管理',{exact:true}).first().click();
  await page.getByText('开发工具',{exact:true}).first().click();
  const documentResponse = page.waitForResponse(response => new URL(response.url()).pathname === '/api/openapi.json');
  await page.getByText('接口调试', {exact:true}).first().click();
  expect((await documentResponse).status()).toBe(200);
  await expect(page.getByText(/接口目录/)).toBeVisible();
  await page.getByLabel('GET /api/health', {exact:true}).click();
  await page.getByRole('button', {name:'发送请求'}).click();
  await expect(page.getByText('HTTP 200', {exact:true})).toBeVisible();
  await expect(page.getByRole('region', {name:'响应 JSON'}).getByText('connected', {exact:true})).toBeVisible();
  await page.getByLabel('GET /api/auth/me', {exact:true}).click();
  await page.getByRole('tab', {name:'认证',exact:true}).click();
  await page.getByText('不携带认证', {exact:true}).click();
  await page.getByRole('button', {name:'发送请求'}).click();
  await expect(page.getByText('HTTP 401', {exact:true})).toBeVisible();
  expect(page.url()).toContain('/api-debug');
  await page.getByRole('radio', {name:'当前登录身份',exact:true}).click();
  await page.getByRole('button', {name:'发送请求'}).click();
  await expect(page.getByText('HTTP 200', {exact:true})).toBeVisible();
  await page.getByText('临时 Bearer Token', {exact:true}).click();
  await page.getByLabel('临时 Token').fill('invalid-debug-token');
  await page.getByRole('button', {name:'发送请求'}).click();
  await expect(page.getByText('HTTP 401', {exact:true})).toBeVisible();
  await page.getByRole('radio', {name:'当前登录身份',exact:true}).click();
  await page.getByPlaceholder('搜索路径、说明、分组').fill('admin/app-users/{id}');
  await page.getByLabel('GET /api/admin/app-users/{id}', {exact:true}).click();
  await page.getByLabel('id', {exact:true}).fill('00000000-0000-0000-0000-000000000000');
  await page.getByRole('button', {name:'发送请求'}).click();
  await expect(page.getByText('HTTP 404', {exact:true})).toBeVisible();
  await page.getByPlaceholder('搜索路径、说明、分组').fill('');
  await page.getByLabel('POST /api/admin/app-users', {exact:true}).click();
  await expect(page.getByRole('tab', {name:'请求体',exact:true})).toHaveAttribute('aria-selected','true');
  await expect(page.getByRole('region', {name:'JSON 请求体'})).toContainText('demo_user');
  await page.getByRole('region', {name:'JSON 请求体'}).locator('.cm-content[contenteditable=true]').fill('{bad json');
  await page.getByRole('button', {name:'发送请求'}).click();
  await expect(page.getByRole('alert').last()).toBeVisible();
  await page.getByLabel('最近请求').first().click();
  await page.getByText('404 · GET /api/admin/app-users/{id}', {exact:true}).click();
  await expect(page.getByText('404 · GET /api/admin/app-users/{id}', {exact:true})).toBeHidden();
  await expect(page.getByLabel('id', {exact:true})).toHaveValue('00000000-0000-0000-0000-000000000000');
  await page.getByLabel('GET /api/health', {exact:true}).click();
  await page.getByRole('button', {name:'发送请求'}).click();
  await expect(page.getByText('HTTP 200', {exact:true})).toBeVisible();
  await page.getByRole('tab', {name:/请求头/}).click();
  await page.getByRole('button', {name:'添加请求头'}).click();
  await page.getByLabel('请求头名称').fill('X-Debug');
  await page.getByRole('button', {name:'删除请求头 X-Debug'}).click();
  await expect(page.getByLabel('请求头名称')).toHaveCount(0);
  await page.getByText('文档', {exact:true}).click();
  await expect(page.getByRole('heading', {name:'响应定义',exact:true})).toBeVisible();
  await expect(page.getByText('检查服务和数据库连接是否可用；数据库不可用时返回 503。无需登录。',{exact:true})).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('api-contract-document.png'),fullPage:true});
  await page.getByText('调试', {exact:true}).click();
  await page.getByRole('tab', {name:/参数/}).click();
  await page.getByLabel('GET /api/admin/accounts', {exact:true}).click();
  await page.getByRole('button', {name:'发送请求'}).click();
  await expect(page.getByText('HTTP 200', {exact:true})).toBeVisible();
  await expect(page.getByRole('tab', {name:/参数/})).toHaveAttribute('aria-selected','true');
  await page.screenshot({path:testInfo.outputPath('desktop.png'),fullPage:true,animations:'disabled'});
  console.log('desktop', await page.evaluate(() => ({scrollWidth:document.documentElement.scrollWidth, width:innerWidth, scrollHeight:document.documentElement.scrollHeight,height:innerHeight})));
  await page.setViewportSize({width:1280,height:768});
  await page.screenshot({path:testInfo.outputPath('compact.png'),fullPage:true,animations:'disabled'});
  console.log('compact', await page.evaluate(() => ({scrollWidth:document.documentElement.scrollWidth, width:innerWidth, scrollHeight:document.documentElement.scrollHeight,height:innerHeight})));
  expect(errors).toEqual([]);

  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(1280);
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBe(768);
  await page.route('**/api/debug/execute', route => { void new Promise(resolve => setTimeout(resolve, 1000)).then(() => route.abort()).catch(() => {}); });
  await page.getByRole('button', {name:'发送请求'}).click();
  await page.getByRole('button', {name:'取消等待'}).click();
  await expect(page.getByText('已取消等待。服务端已经发生的修改不会撤销。', {exact:true})).toBeVisible();
  await page.unroute('**/api/debug/execute');
  await page.getByText('上下', {exact:true}).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(1280);
  await page.getByText('左右', {exact:true}).click();
  await page.getByLabel('POST /api/admin/app-users', {exact:true}).click();
  const bodyEditor = page.getByRole('region', {name:'JSON 请求体'}).locator('.cm-content[contenteditable=true]');
  await bodyEditor.fill('{"account":"latest_editor_value"}');
  await page.getByRole('button', {name:'清空',exact:true}).click();
  await expect(page.getByText('覆盖当前已编辑的请求体？', {exact:true})).toBeVisible();
  await page.getByRole('button', {name:'取 消',exact:true}).click();
  await expect(bodyEditor).toContainText('latest_editor_value');
  let sentBody: string | undefined;
  await page.route('**/api/debug/execute', async route => {
    sentBody = route.request().postDataJSON().body;
    await route.fulfill({json:{status:200,duration:1,headers:{},body:'{}'}});
  });
  await page.getByRole('button', {name:'发送请求'}).click();
  await expect.poll(() => sentBody).toBe('{"account":"latest_editor_value"}');
  await page.unroute('**/api/debug/execute');
  expect(errors).toEqual([]);

});
